steps:
  - name: 'Build packages'
    command: './script/build'
    artifact_paths: bin/**/*
    plugins:
      docker-compose#v2.2.1:
        run: cli

  - wait

  - name: ":mag:"
    command: "./script/extract-cli-version"
    env:
      CALIBRE_API_TOKEN: noop

  - wait

  - name: ":s3: publish binaries"
    command: "script/publish"
    if: |
      env("BUILDKITE_TAG") != ""
