#!/bin/bash

set -euo pipefail

echo "--- Building packages"
rm -rf bin
mkdir -p bin/{mac,windows,linux}
pkg . --out-path=bin

echo "--- Renaming binaries"
mv bin/calibre-macos bin/mac/calibre
mv bin/calibre-win.exe bin/windows/calibre.exe
mv bin/calibre-linux bin/linux/calibre
