#!/bin/bash

set -euo pipefail

ARTIFACT_NAME="bin/linux/calibre"
BIN_PATH="packages/bin/linux/calibre"

echo '--- Downloading built cli'

mkdir -p packages
buildkite-agent artifact download "${ARTIFACT_NAME}" packages

chmod +x "${BIN_PATH}"

echo '+++ Extracting cli version from binary'

CLI_VERSION=$("${BIN_PATH}" --version)

echo "Full cli version: $CLI_VERSION"

buildkite-agent meta-data set "cli-version" "$CLI_VERSION"
