#!/bin/bash

set -euo pipefail

BIN_NAME="bin/linux/calibre"

echo '--- Downloading built cli'

mkdir -p packages
buildkite-agent artifact download "${BIN_NAME}" packages
ls packages
chmod +x "packages/calibre"

echo '+++ Extracting cli version from binary'

CLI_VERSION=$(packages/calibre --version)

echo "Full cli version: $CLI_VERSION"

buildkite-agent meta-data set "cli-version" "$CLI_VERSION"
