name: Test Node.js

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm link
      - run: |
          # ESLint is broken on Node.js 16.x
          # ESLint throws punycode errors on 22.x
          if [[ "${{ matrix.node-version }}" == "18.x" || "${{ matrix.node-version }}" == "20.x" ]]; then
            npm run lint
          fi
